Repository ng-bootstrap/ng-bootstrap, pull requests merged in 2019-03, with the labels that each got.

#3047 docs: add missing 'since' annotations for 4.1.0
  src/dropdown/dropdown.ts
  src/popover/popover.ts
  src/tooltip/tooltip.ts
Labels: type: doc

#3044 feat(datepicker): make '(navigate)' event cancellable
  src/datepicker/datepicker-input.spec.ts
  src/datepicker/datepicker-input.ts
  src/datepicker/datepicker-service.spec.ts
  src/datepicker/datepicker-service.ts
  src/datepicker/datepicker.spec.ts
  src/datepicker/datepicker.ts
Labels: component: datepicker, needs: review

#3053 chore: remove gulp tasks from the releasing process
  gulpfile.js
  package.json
  yarn.lock
Labels: needs: merging, type: build

#3045 docs: update readme
  README.md
Labels: needs: review, type: doc

#3067 fix(docs): change day variable to correct argument reference
  demo/src/app/components/datepicker/overview/datepicker-overview.component.ts
Labels: type: doc

#3065 chore: cleanup unused imports in 'index.ts'
  src/index.ts
Labels: needs: merging

#3068 chore: extract module name and component selector for stackblitz
  .travis.yml
  misc/parse-demo-test-cases/no-bootstrap-component/test.component.ts
  misc/parse-demo-test-cases/no-bootstrap-component/test.module.ts
  misc/parse-demo-test-cases/no-component-selector/test.component.ts
  misc/parse-demo-test-cases/no-component-selector/test.module.ts
  misc/parse-demo-test-cases/no-module/test.component.ts
  misc/parse-demo-test-cases/simple/test.component.ts
  misc/parse-demo-test-cases/simple/test.module.ts
  misc/parse-demo-test-cases/syntax/test.component.ts
  misc/parse-demo-test-cases/syntax/test.module.ts
  misc/parse-demo.spec.ts
  misc/parse-demo.ts
  package.json
Labels: type: build, type: demo site

#3069 chore: update demo parsing for stackblitzes
  misc/parse-demo-test-cases/multiple/one/test.component.ts
  misc/parse-demo-test-cases/multiple/one/test.module.ts
  misc/parse-demo-test-cases/multiple/two/test.component.ts
  misc/parse-demo-test-cases/multiple/two/test.module.ts
  misc/parse-demo.spec.ts
  misc/parse-demo.ts
Labels: needs: review, type: build, type: demo site

#3085 fix(aria): set radio buttons role as "radiogroup"
  src/buttons/radio.spec.ts
  src/buttons/radio.ts
Labels: component: buttons, needs: review

#3049 fix(tests): remove unexpected elements between tests
  src/popover/popover.spec.ts
  src/test/global.spec.ts
  src/tooltip/tooltip.spec.ts
  src/util/positioning.spec.ts
Labels: needs: merging, type: tests

#3074 fix(positioning): round translated positions
  src/util/positioning.ts
Labels: needs: merging

#3058 fix(dropdown): wrong positioning calculation
  src/dropdown/dropdown.spec.ts
  src/dropdown/dropdown.ts
Labels: component: dropdown

#3064 fix(datepicker): export Gregorian calendar
  src/datepicker/datepicker.module.ts
  src/index.ts
Labels: component: datepicker

#3089 fix(autoclose): take into account inside 'touch' events on iOS
  src/util/autoclose.ts
Labels: component: datepicker, type: bug
