Repository ng-bootstrap/ng-bootstrap, pull requests merged in 2020-10, with the labels that each got.

#3862 refactor(animations): put transitions next to respective components
  src/alert/alert-transition.ts
  src/alert/alert.ts
  src/nav/nav-outlet.ts
  src/nav/nav-transition.ts
  src/toast/toast-transition.ts
  src/toast/toast.ts
  src/util/transition/ngbFadingTransition.ts
Labels: type: animation

#3864 fix(animations): make collapsing transition work with SSR
  src/util/transition/ngbCollapseTransition.ts
Labels: type: animation, type: bug, type: ssr

#3865 docs: since annotations for 8.0.0
  src/accordion/accordion-directives.ts
  src/accordion/accordion.ts
  src/alert/alert.ts
  src/carousel/carousel.ts
  src/collapse/collapse.ts
  src/modal/modal-config.ts
  src/modal/modal-ref.ts
  src/nav/nav.ts
  src/popover/popover.ts
  src/toast/toast.ts
  src/tooltip/tooltip.ts
Labels: type: doc

#3876 refactor(rating): simplify _getFillValue implementation
  src/rating/rating.ts
Labels: component: rating, needs: merging

#3877 Minor rating changes
  src/rating/rating.ts
Labels: component: rating
