Repository ng-bootstrap/ng-bootstrap, pull requests merged in 2020-03, with the labels that each got.

#3636 ci: bump SauceLabs to latest Edge and Safari
  src/karma.sauce.conf.js
Labels: type: build

#3639 test: e2e demo tests fail on small screens
  demo/src/app/components/components.e2e-spec.ts
  demo/src/app/tools.po.ts
Labels: needs: merging, type: tests

#3644 fix(dropdown): ngbDropdown adds vertical scrollbar ... (#3580)
  src/dropdown/dropdown.ts
  src/util/positioning.spec.ts
  src/util/positioning.ts
Labels: component: dropdown

#3655 revert: fix(dropdown): ngbDropdown adds scrollbars (#3644)
  src/dropdown/dropdown.ts
  src/util/positioning.spec.ts
  src/util/positioning.ts
Labels: needs: merging

#3656 demo: fix routerLinks broken with #3641
  demo/src/app/components/shared/api-docs/api-docs-class.component.html
  demo/src/app/components/shared/api-docs/api-docs-config.component.html
  demo/src/app/components/shared/api-docs/api-docs.component.html
  demo/src/app/components/shared/examples-page/demo.component.html
  demo/src/app/components/shared/overview/overview-section.component.ts
  demo/src/app/shared/page-wrapper/page-header.component.ts
  demo/src/app/shared/page-wrapper/page-wrapper.component.html
Labels: needs: merging, type: demo, type: regression
