Repository ng-bootstrap/ng-bootstrap, pull requests merged in 2021-11, with the labels that each got.

#4180 build: replace ngx-build-plus with @angular-builders/custom-webpack
  angular.json
  e2e-app/coverage.webpack.js
  package.json
  yarn.lock
Labels: needs: merging, type: build

#4174 docs: fix typo
  demo/src/app/pages/animations/animations.component.html
Labels: type: doc

#4163 docs(datepicker): add NgbCalendarBuddhist in other calendar list
  demo/src/app/components/datepicker/calendars/datepicker-calendars.component.ts
Labels: needs: review, type: doc

#4183 build: fix and re-enable schematics unit tests
  package.json
  schematics/ng-add/index.spec.ts
  schematics/tsconfig.json
  yarn.lock
Labels: needs: merging, type: build
